ossgg: side quest social-poster-here link add to file
OpenBB-finance/OpenBB pull request #6913
Opened 2024-10-30 06:34 UTC by adityadeshlahre

- #6912 

### Social hero
![image](https://github.com/user-attachments/assets/64231535-6fcb-4022-9e0e-a1bbf9b1d339)

### Social Poster
![image](https://github.com/user-attachments/assets/6ca6e44f-fc19-44ab-973b-23d893b7046a)

2024-10-30 06:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenBB-finance/OpenBB?pullRequest=6913) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenBB-finance/OpenBB?pullRequest=6913) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenBB-finance/OpenBB?pullRequest=6913) it.</sub>

2024-10-30 20:55 UTC, jmaslek approved these changes

2024-10-30 20:55 UTC, jmaslek commented
/award 150

2024-10-30 21:18 UTC, adityadeshlahre commented
hey @jmaslek i think you have missed my point for article :slightly_smiling_face:

2024-10-31 14:25 UTC, piiq commented
The blog post is deeply wrong factually. It is not accepted. Please remove it from the submission if you want this PR to be merged by the end of the day

2024-10-31 14:26 UTC, piiq commented
nvm, I did it for you

2024-10-31 14:27 UTC, piiq requested changes
Remove the dev.to post from the PR please

2024-10-31 14:27 UTC, piiq commented on oss.gg/no_code_side_quests/5-financial-post.md
> +» 30-October-2024 by aditya deshlahre » Link to Article: [article](https://dev.to/adityadeshlahre/redefining-financial-analysis-with-openbb-the-power-of-open-source-versus-proprietary-tools-2j2p)
Remove this post from the submission please. It is not accepted

2024-10-31 14:28 UTC, piiq approved these changes

2024-10-31 14:32 UTC, merged